// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsDmO5xbIhe7OTHToLwNbcwdsmr5-D0g',
    appId: '1:857087533390:web:f1daccf85a13215163fe1f',
    messagingSenderId: '857087533390',
    projectId: 'meb-stock-program',
    authDomain: 'meb-stock-program.firebaseapp.com',
    storageBucket: 'meb-stock-program.appspot.com',
    measurementId: 'G-FQ4BR1PN0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0sZeu2bBZQOse5KIKQgN3MdOB2UKuFs',
    appId: '1:857087533390:android:c026dfaffa38b8cf63fe1f',
    messagingSenderId: '857087533390',
    projectId: 'meb-stock-program',
    storageBucket: 'meb-stock-program.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_NytMzIx97mLyjXU-NJgicfPVRuHpQm8',
    appId: '1:857087533390:ios:646e9010b80be56163fe1f',
    messagingSenderId: '857087533390',
    projectId: 'meb-stock-program',
    storageBucket: 'meb-stock-program.appspot.com',
    iosBundleId: 'com.example.mebStockProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_NytMzIx97mLyjXU-NJgicfPVRuHpQm8',
    appId: '1:857087533390:ios:646e9010b80be56163fe1f',
    messagingSenderId: '857087533390',
    projectId: 'meb-stock-program',
    storageBucket: 'meb-stock-program.appspot.com',
    iosBundleId: 'com.example.mebStockProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVsDmO5xbIhe7OTHToLwNbcwdsmr5-D0g',
    appId: '1:857087533390:web:e554c2f650870b1063fe1f',
    messagingSenderId: '857087533390',
    projectId: 'meb-stock-program',
    authDomain: 'meb-stock-program.firebaseapp.com',
    storageBucket: 'meb-stock-program.appspot.com',
    measurementId: 'G-7T1S2S2046',
  );
}
